/* Generated By:JavaCC: Do not edit this line. Example1Constants.java */
package egtry;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Example1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<INT>",
    "\"a\"",
    "\"b\"",
    "\"c\"",
    "\"d\"",
    "\"e\"",
    "\"f\"",
    "\"(\"",
    "\"+\"",
    "\"-\"",
    "\")\"",
    "\"==\"",
    "\"^\"",
    "\"tt\"",
    "\"ff\"",
    "\"!\"",
    "\"skip\"",
    "\";\"",
    "\":=\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
  };

}
